[package]
name = "vir-conformance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
vir-codec = { path = "../vir-codec" }
vir-runtime = { path = "../vir-runtime" }
vir-types = { path = "../vir-types" }

[lints]
workspace = true

