"""
VAMS SIRA Engine
================
Implements Superintelligent Retrieval Agent (SIRA) single-shot lexical retrieval
with Document Frequency (DF) filtering and dual-weighted BM25 scoring.

Reference: arXiv:2605.06647
"""

import math
import re
from typing import List, Dict, Tuple, Set, Optional, Any

class SimpleBM25:
    """
    A lightweight, pure-Python implementation of BM25 for indexing memory documents.
    """
    def __init__(self, k1: float = 1.5, b: float = 0.75):
        self.k1 = k1
        self.b = b
        self.documents: List[Dict[str, Any]] = []  # List of {"id": str, "text": str, "terms": List[str]}
        self.corpus_size = 0
        self.avg_doc_len = 0.0
        self.doc_lengths: List[int] = []
        self.doc_freqs: Dict[str, int] = {}  # Term -> Doc count
        self.term_freqs: List[Dict[str, int]] = []  # List of {Term -> Count} per doc

    def tokenize(self, text: str) -> List[str]:
        """Convert text into normalized lowercase word tokens."""
        return re.findall(r'[a-zA-Z0-9_\-]+', text.lower())

    def add_document(self, doc_id: str, text: str):
        """Add a document to the index."""
        terms = self.tokenize(text)
        doc_len = len(terms)
        
        term_freq: Dict[str, int] = {}
        unique_terms: Set[str] = set()
        
        for term in terms:
            term_freq[term] = term_freq.get(term, 0) + 1
            unique_terms.add(term)
            
        for term in unique_terms:
            self.doc_freqs[term] = self.doc_freqs.get(term, 0) + 1
            
        self.documents.append({"id": doc_id, "text": text, "terms": terms})
        self.doc_lengths.append(doc_len)
        self.term_freqs.append(term_freq)
        
        self.corpus_size = len(self.documents)
        self.avg_doc_len = sum(self.doc_lengths) / max(1, self.corpus_size)

    def idf(self, term: str) -> float:
        """Calculate inverse document frequency with smoothing."""
        df = self.doc_freqs.get(term, 0)
        # Standard BM25 IDF formula
        return math.log((self.corpus_size - df + 0.5) / (df + 0.5) + 1.0)

    def df(self, term: str) -> int:
        """Get the Document Frequency of a term."""
        return self.doc_freqs.get(term, 0)

    def doc_score(self, query_terms: List[str], doc_index: int) -> float:
        """Calculate BM25 score for a single document against a list of terms."""
        score = 0.0
        doc_len = self.doc_lengths[doc_index]
        term_freq = self.term_freqs[doc_index]
        
        for term in query_terms:
            if term not in term_freq:
                continue
            tf = term_freq[term]
            idf_val = self.idf(term)
            
            numerator = tf * (self.k1 + 1)
            denominator = tf + self.k1 * (1.0 - self.b + self.b * (doc_len / max(1.0, self.avg_doc_len)))
            score += idf_val * (numerator / denominator)
            
        return score


class SiraEngine:
    """
    SIRA Engine implementing expected-response sketch expansion,
    DF pruning, and dual BM25 scoring:
    Score(d) = BM25(q_orig, d) + w * BM25(q_exp, d)
    """
    def __init__(self, k1: float = 1.5, b: float = 0.75):
        self.bm25 = SimpleBM25(k1=k1, b=b)

    def add_document(self, doc_id: str, text: str):
        """Index a document."""
        self.bm25.add_document(doc_id, text)

    def retrieve(
        self, 
        query_orig: str, 
        q_exp_terms: List[str], 
        w: float = 1.2, 
        tau: float = 0.5,
        top_n: int = 5
    ) -> List[Tuple[str, float]]:
        """
        Perform SIRA single-shot retrieval.
        
        Args:
            query_orig: Original search query.
            q_exp_terms: Expansion terms from expected-response sketch (generated by LLM).
            w: Scaling factor weight for the expansion query group.
            tau: Document Frequency filtering ratio (0 < DF <= tau * |C|).
            top_n: Number of results to return.
            
        Returns:
            List of (doc_id, score) sorted in descending order of score.
        """
        if self.bm25.corpus_size == 0:
            return []

        # Tokenize original query
        q_orig_terms = self.bm25.tokenize(query_orig)

        # Apply DF filtering on expansion terms
        # 0 < DF <= tau * Corpus Size
        max_df = max(1.0, tau * self.bm25.corpus_size)
        filtered_q_exp = [
            term for term in q_exp_terms
            if 0 < self.bm25.df(term) <= max_df
        ]

        results: List[Tuple[str, float]] = []
        for i, doc in enumerate(self.bm25.documents):
            score_orig = self.bm25.doc_score(q_orig_terms, i)
            score_exp = self.bm25.doc_score(filtered_q_exp, i)
            
            # SIRA Dual Scoring formula
            total_score = score_orig + w * score_exp
            if total_score > 0.0:
                results.append((doc["id"], total_score))


        # Sort by score descending
        results.sort(key=lambda x: x[1], reverse=True)
        return results[:top_n]
